### PR TITLE
ISSUE-37: user extensible kinds

### PR DESCRIPTION
**Pull request by jjtolton**
Closes: https://github.com/scicloj/notespace/issues/37

I can't figure out the best way to run the tests or ensure functionality, so I'm going to leave this as a draft until I have some better insight into how to test.  Would love comments on the approach!

### CODE REVIEW

**Comment by daslu** [comment]
@jjtolton wonderful, I'll merge this.

A few comments:

* One related thing that is hard-coded at the moment is the built-in rules for inferring a note's kind:
https://github.com/scicloj/notespace/blob/71c04bd448ab42055aee07649a1f7c34eed740c1/src/notespace/note.clj#L78

* It may be nice to express user definitions as changes in the config state through the `api/update-config` function:
https://github.com/scicloj/notespace/blob/71c04bd448ab42055aee07649a1f7c34eed740c1/src/notespace/api.clj#L13
That would make sure that such changes pass through the (cljfx-based) event system. This can be useful in the future for recording user sessions, undoing changes, etc.
At the moment, it is not so important. Just mentioning it so that we have that option in mind.

**Comment by daslu** [comment]
(Oh, sorry, I see you've marked it as draft. Not merging yet.)

**Comment by behrica** [comment]
> Closes: #37
> 
> I can't figure out the best way to run the tests or ensure functionality, so I'm going to leave this as a draft until I have some better insight into how to test. Would love comments on the approach!

I started writing some tests.
They are in fact "integration tests" more then unit tests.
Using the `lifecycle/init` + functions in `actions` should allow to trigger the evaluation of any notespace file.
And the you can "test" in the list of notes in the 'state'

See here: 
https://github.com/scicloj/notespace/blob/master/test/notespace/note_test.clj
https://github.com/scicloj/notespace/blob/71c04bd448ab42055aee07649a1f7c34eed740c1/test/notespace/actions_test.clj#L8

**Comment by jjtolton** [comment]
Tested successfully -- can't detect any regressions.  @daslu was able to get it working locally.  Moving out of draft status.

**Comment by behrica** [comment]
This change introduces an error evaluating the experiment notespace:

java.lang.IllegalArgumentException: No method in multimethod 'kind->behaviour' for dispatch value: :notespace.kinds/big
from this line:

https://github.com/scicloj/notespace/blob/fe4a055e059d9c9e9f9cf77240fb62a57a80b6ee/test/notespace/v3_experiment1_test.clj#L439

Do we need to define the kind "big" here now ?

**Comment by jjtolton** [comment]
I see this on the new PR: 
image
What symptoms are you seeing that this doesn't work @behrica ?

**Pull request merged**
